#!/usr/bin/expect -f
#Autogenerated by autoexpect
#
# 1) timing

set force_conservative 0  ;# set to 1 to force conservative mode even if
                          ;# script wasnt run conservatively originally
if {$force_conservative} {
        set send_slow {1 .1}
        proc send {ignore arg} {
                sleep .1
                exp_send -s -- $arg
        }
}

#Diferring output

set timeout -1
spawn vncpasswd
match_max 100000
expect -exact "Using password file /home/vncer/.vnc/passwd\r
Password: "
send -- "deleteme\r"
expect -exact "\r
Verify:   "
send -- "deleteme\r"
expect -exact "\r
Would you like to enter a view-only password (y/n)? "
send -- "n\r"
expect eof
